# core/html_report.py

import os
from datetime import datetime

def generate_html(username, results, correlation):
    """Professional HTML report with dark theme, contacts, and correlation."""

    rows = ""
    for r in results:
        contacts_html = ""
        contacts = r.get("contacts", {})
        if contacts.get("emails"):
            contacts_html += f"<br><strong>Emails:</strong> {', '.join(contacts['emails'])}"
        if contacts.get("phones"):
            contacts_html += f"<br><strong>Phones:</strong> {', '.join(contacts['phones'])}"

        bio = r.get("bio") or ""
        bio = bio.replace("\n", "<br>")

        status_color = "#2ecc71" if r["status"] == "FOUND" else "#e74c3c" if r["status"] == "ERROR" else "#95a5a6"

        rows += f"""
        <tr>
            <td>{r['platform']}</td>
            <td style="color:{status_color}; font-weight:bold;">{r['status']}</td>
            <td>{r['confidence']}%</td>
            <td class="bio">{bio}{contacts_html}</td>
        </tr>
        """

    correlation_html = ""
    if correlation:
        for bio_text, platforms in correlation.items():
            preview = bio_text[:120]
            correlation_html += f"<li><strong>{preview}...</strong> → Platforms: {', '.join(platforms)}</li>"
    else:
        correlation_html = "<li>No correlations found.</li>"

    html_content = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Silica-X Report - {username}</title>
        <style>
            body {{ background-color: #1e1e1e; color: #eaeaea; font-family: Arial, sans-serif; padding: 20px; }}
            h1 {{ color: #00ffff; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
            th, td {{ border: 1px solid #333; padding: 10px; text-align: left; vertical-align: top; }}
            th {{ background-color: #2c2c2c; }}
            tr:nth-child(even) {{ background-color: #262626; }}
            .bio {{ max-width: 600px; word-wrap: break-word; font-size: 0.95em; }}
            .section {{ margin-top: 40px; }}
            ul {{ margin-top: 10px; }}
            footer {{ margin-top: 50px; font-size: 0.85em; color: #888; }}
        </style>
    </head>
    <body>
        <h1>Silica-X Report</h1>
        <p><strong>Username:</strong> {username}</p>
        <p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>

        <div class="section">
            <h2>Scan Results</h2>
            <table>
                <tr>
                    <th>Platform</th>
                    <th>Status</th>
                    <th>Confidence</th>
                    <th>Bio / Public Info / Contacts</th>
                </tr>
                {rows}
            </table>
        </div>

        <div class="section">
            <h2>Correlation Analysis</h2>
            <ul>
                {correlation_html}
            </ul>
        </div>

        <footer>
            Generated by Silica-X | Developed by voltsparx
        </footer>
    </body>
    </html>
    """

    path = f"output/{username}"
    os.makedirs(path, exist_ok=True)
    report_file = f"{path}/report.html"
    with open(report_file, "w", encoding="utf-8") as f:
        f.write(html_content)

    return report_file
